#!/bin/zsh

CP=$(pwd)
cp ~/.zshrc ~/dot_files
cp ~/.tmux.conf ~/dot_files
cp ~/.config/nvim/init.vim ~/dot_files/.config/nvim
cp ~/.i3/config ~/dot_files/.i3/
cp ~/.xmodmap_60 ~/dot_files
cp ~/.Xresources ~/dot_files
cp ~/.config/aliasrc ~/dot_files
cp ~/.scripts/* ~/dot_files/.scripts
cd ~/dot_files
echo "dot files copied!"
cd $CP
