#!/bin/sh
# thanks https://github.com/CalinLeafshade for the idea

noteFilename="$HOME/notes/note.md"

if [ ! -f $noteFilename ]; then
  echo "# Notes for $(date +%Y-%m-%d)" > $noteFilename
fi

nvim -c "norm Go" \
  -c "norm Go## $(date +%H:%M)" \
  -c "norm G2o" \
  -c "norm zz" \
  -c "norm i" $noteFilename

